### ISSUE TITLE
get rid of code in the database

### ISSUE THREAD

**Issue by connorbode** [connorbode/datastructor#10]
Well.  Turns out storing the code inside the database was an absolutely shitty idea.  So, it's time to eliminate that feature.  The following are things that need to be done:
## Tasks
- [x] Edit the sequence model, changing type to a string
- [x] Delete the operation and data-structure models
- [x] Delete all tasks related to operations and data structures
- [x] Delete the data structure endpoint
- [x] Remove all references to data structures from the sequences endpoints
- [x] Delete all references to the data structures model
- [x] Remove `public/actions/StructureActions` and references to it.
- [x] Modify `constants/StructureConstants` to contain constants referring to structure edit views, structure edit types, etc.  
- [x] Remove `public/components/views/DataStructureEdit`, `public/components/views/DataStructureList`, `public/components/views/DataStructureNew` and references to them.
- [x] Remove `public/stores/StructureStore` and all references to it
- [x] Modify `public/components/views/SequenceNew` to list the types available from `StructureConstants`
